### ISSUE TITLE
代理端口无法上网

### ISSUE THREAD

**Issue by pan8664716** [momosecurity/Mloger#3]
访问任何网络都会报错：
首先连证书下载都无法进行：
Addon error: Traceback (most recent call last):
  File "/home/star/.pyenv/versions/3.9.0/envs/mlogger-python-3.9.0/lib/python3.9/site-packages/mitmproxy/script/concurrent.py", line 30, in _concurrent
    obj.reply.take()
  File "/home/star/.pyenv/versions/3.9.0/envs/mlogger-python-3.9.0/lib/python3.9/site-packages/mitmproxy/controller.py", line 41, in take
    raise exceptions.ControlException(f"Reply is {self.state}, but expected it to be start.")
mitmproxy.exceptions.ControlException: Reply is taken, but expected it to be start.

**Comment by ResidualLaugh** [comment]
复现场景：我成功复现了这个报错，它发生在 “没有在准入代理功能中授权ip而直接通过代理访问网址” 的情况下。
解决方法：在准入代理功能对ip授权后，可以正常访问网络，并且不会发生报错。

你可以在授权ip后重试，如果依旧有报错，请告知我。

**Comment by pan8664716** [comment]
> 复现场景：我成功复现了这个报错，它发生在 “没有在准入代理功能中授权ip而直接通过代理访问网址” 的情况下。 解决方法：在准入代理功能对ip授权后，可以正常访问网络，并且不会发生报错。
> 
> 你可以在授权ip后重试，如果依旧有报错，请告知我。

感谢回复，问题得到解决！
已经通过在页面 准入代理 功能入口，将手机ip接入后，可以访问！
